"""Generates a training config directly from a released checkpoint's hparams.yaml.

Every value that exists in the official hparams is copied verbatim; nothing is
hand-maintained. Keys that the official hparams do NOT contain (distortion
parameter values, data paths) are emitted under explicit "inferred" /
"user-must-set" markers.

Mapping notes (derived, with the reasoning recorded here):
  - end_token: the inference code (server.letters_encoding) writes chars as
    message+1 with 0 reserved for the end token, requiring message_dim >= 5
    for 2-bit chars. The released 44k hparams have message_dim 5 (end token),
    the released 16k hparams have message_dim 4 (no end token).
  - distortions/compression: mp3_aug / ogg_aug / aac_aug are either false or a
    string like "64k,128k,256k". Enabled codecs and their bitrates are taken
    from these flags.
  - gaussian noise: add_carrier_noise: gaussian with carrier_noise_norm: 0.01
    in the official hparams; carrier_noise_norm is copied for reference.

Usage:
    python train/make_config_from_release.py \
        --release_dir Models/44_1_khz/73999_iteration --out train/config_44k.yaml
"""

import argparse
import os

import yaml

COPIED_KEYS = [
    'model_type', 'SR', 'N_FFT', 'HOP_LENGTH', 'message_band_size', 'message_dim',
    'message_len', 'n_messages', 'enc_n_layers', 'dec_c_n_layers', 'message_sdr',
    'ensure_negative_message', 'ensure_constrained_message', 'no_normalization',
    'frame_level_normalization', 'utterance_level_normalization',
    'batch_size', 'num_workers', 'seed', 'carrier_noise_norm',
]


def parse_bitrates(flag):
    """'64k,128k,256k' -> [64, 128, 256]; false/None -> []"""
    if not flag or flag is False:
        return []
    return [int(b.strip().rstrip('k')) for b in str(flag).split(',')]


def build_config(hp):
    config = {k: hp[k] for k in COPIED_KEYS if k in hp}

    config['learning_rate'] = hp['lr']
    config['duration_seconds'] = hp['AUDIO_LEN']
    config['end_token'] = hp['message_dim'] >= 5

    codecs, bitrates = [], []
    for codec, key in [('mp3', 'mp3_aug'), ('ogg', 'ogg_aug'), ('aac', 'aac_aug')]:
        rates = parse_bitrates(hp.get(key))
        if rates:
            codecs.append(codec)
            bitrates = sorted(set(bitrates) | set(rates))

    distortions = ['none', 'gaussian_noise', 'time_jitter', 'equalization']
    if codecs:
        distortions.append('compression')
    config['distortions'] = distortions
    config['compression_codecs'] = codecs
    config['compression_bitrates'] = bitrates

    # --- Not present in the released hparams: inferred or user-provided ----
    config['num_iterations'] = 80000          # paper Sec. 4; releases: 44k=74k, 16k=81.5k+16k finetune
    config['gaussian_snr_db'] = 40            # paper's additive-noise level; exact train-time use unknown
    config['max_jitter_samples'] = 50         # inferred, undocumented
    config['eq_gain_db'] = 15                 # paper: 15 dB band-limited EQ
    config['eq_center_freqs'] = [35, 200, 1000, 4000]  # paper's evaluation EQ bands
    config['message_sdr_range'] = None        # optional [min, max] to randomize alpha
    config['grad_clip'] = None
    config['device'] = 'cuda'
    # Memory/throughput knobs for small GPUs (e.g. 8 GB RTX 2080):
    # amp: true + batch_size: 1 + grad_accum_steps: <official batch> keeps the
    # effective batch while fitting memory. activation_checkpointing is a last
    # resort (doubles BatchNorm running-stat updates).
    config['amp'] = False
    config['grad_accum_steps'] = 1
    config['activation_checkpointing'] = False
    config['data_dirs'] = ['data/train']      # USER MUST SET
    config['val_dirs'] = None                 # optional, e.g. [data/val]
    config['output_dir'] = 'Models/retrained'
    config['log_every'] = 50
    config['save_every'] = 2000
    config['eval_every'] = 2000
    config['eval_batches'] = 8
    config['average_energy'] = 0.002837200844477648  # server.Model.average_energy_VCTK

    return config


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--release_dir', required=True)
    parser.add_argument('--out', required=True)
    args = parser.parse_args()

    hparams_path = os.path.join(args.release_dir, 'hparams.yaml')
    with open(hparams_path) as f:
        hp = yaml.safe_load(f)

    config = build_config(hp)

    header = (f'# Generated by make_config_from_release.py from {hparams_path}\n'
              f'# Values present in the official hparams are copied verbatim.\n'
              f'# data_dirs / output_dir must be set by the user. See the script\n'
              f'# docstring for which remaining values are inferred.\n')
    with open(args.out, 'w') as f:
        f.write(header)
        yaml.safe_dump(config, f, sort_keys=False)
    print(f'wrote {args.out}')
    print(f"  copied from release: SR={config['SR']} message_dim={config['message_dim']} "
          f"message_len={config['message_len']} end_token={config['end_token']} "
          f"batch={config['batch_size']} lr={config['learning_rate']} seed={config['seed']}")
    print(f"  distortions: {config['distortions']} codecs={config['compression_codecs']} "
          f"bitrates={config['compression_bitrates']}")


if __name__ == '__main__':
    main()
